# Generated by Django 6.0.4 on 2026-05-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_price_at_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='order_items',
        ),
    ]
